### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by klattimer** [grieve/python-lgtv#1]
I try to run the example, it finds my tv but I get a connection refused error

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    remote = Remote(address)
  File "/home/pi/SmartSpaces_Interrogator/python-lgtv/lg.py", line 33, in __init__
    self.request_pair()
  File "/home/pi/SmartSpaces_Interrogator/python-lgtv/lg.py", line 111, in request_pair
    self.make_request('/roap/api/auth', content)
  File "/home/pi/SmartSpaces_Interrogator/python-lgtv/lg.py", line 95, in make_request
    http.request("POST", endpoint, content, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by LaggAt** [comment]
Same here. Any solution?

**Comment by klattimer** [comment]
@LaggAt - https://github.com/klattimer/LGWebOSRemote I wrote a working one instead.

**Comment by LaggAt** [comment]
Thanks, found that already. 
I was fiddling around with many projects, think this is the best for my use. I want to use it from kodi.

I had some issues, e.g. scan failed, auth failed with ip-address, arp missing, Exception when auth is failing. For the last i made a pull request.

Thanks so far.

**Comment by grieve** [comment]
I should update this repo to state that this doesn't support WebOS TVs. They didn't really exist in the wild when this was originally hacked together.
